project_id = "vyqbhilwuuqgcywtlsdf"

[functions.receive-metrics]
verify_jwt = false

[functions.receive-feature]
verify_jwt = false

[functions.create-bitrix-lead]
verify_jwt = false

[functions.update-lead-by-email-utms]
verify_jwt = false

[functions.create-simple-lead]
verify_jwt = false

[functions.upd_lead_status]
verify_jwt = false