// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyqbhilwuuqgcywtlsdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cWJoaWx3dXVxZ2N5d3Rsc2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDcyMTgsImV4cCI6MjA3MDQyMzIxOH0.qf9weE6r5mfpHpPqrexRRYFGhGJurKgBqh3FSwpOyhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});